feat: update vpn script

diff --git a/.scripts/vpn b/.scripts/vpn
--- a/.scripts/vpn
+++ b/.scripts/vpn
@@ -1,95 +1,135 @@
 #!/bin/bash
-#
+
+# Constants
+VPN_CONFIG_PATH="$HOME/.nordvpn/ovpn_udp"
+CREDENTIAL_PATH="$HOME/.nordvpn/credential.txt"
+LOG_FILE="/tmp/nordvpn.log"
+IP_ROUTES=(
+  103.151.121.198 # kscdnoversea-th.inter.71edge.com
+  118.69.17.193 # ads.tiktok.com
+  118.69.17.201 # ads.tiktok.com
+  183.80.211.203 # ads.tiktok.com
+  118.69.17.204 # ads.tiktok.com
+  118.69.17.187 # ads.tiktok.com
+  183.80.211.218 # ads.tiktok.com
+  118.69.17.15 # ads.tiktok.com
+  183.80.211.200 # ads.tiktok.com
+  118.69.17.186 # ads.tiktok.com
+)
+
+IP_DEFAULTS=(
+  34.117.186.192 # ipinfo.io
+  172.67.168.106 # ifconfig.co
+  104.21.54.91 # ifconfig.co
+)
+
 # Function to clean up and exit
 cleanup_and_exit() {
-    echo ""
-    echo "Exiting..."
-    
-    # Kill all running OpenVPN processes
-    if pgrep openvpn >/dev/null; then
+    echo -e "\nExiting..."
+    if pgrep openvpn > /dev/null; then
         if sudo pkill openvpn; then
             echo "All OpenVPN processes killed."
         else
             echo "Failed to kill OpenVPN processes."
         fi
     fi
-    
     exit 1
 }
 
 # Trap Ctrl+C and call cleanup_and_exit function
 trap cleanup_and_exit SIGINT
 
-vpn_config_path="$HOME/.nordvpn/ovpn_udp"
-credential_path="$HOME/.nordvpn/credential.txt"
+# Function to select VPN configuration file
+select_vpn_config() {
+    local selected_filename
+    selected_filename=$(rg --files "$VPN_CONFIG_PATH" | xargs -n1 basename | fzf --prompt="Select VPN config: ")
 
-# Select OpenVPN config file using fzf
-selected_filename=$(rg --files "$vpn_config_path" | xargs -n1 basename | fzf --prompt="Select VPN config: ")
-selected_file="$vpn_config_path/$selected_filename"
+    if [ -z "$selected_filename" ]; then
+        echo ""
+    else
+        echo "$VPN_CONFIG_PATH/$selected_filename"
+    fi
+}
 
-# Exit if no file is selected
-if [ -z "$selected_filename" ]; then
+# Function to update auth-user-pass in the configuration file
+update_auth_user_pass() {
+    local file=$1
+    local line_number
+    line_number=$(grep -n 'auth-user-pass.*' "$file" | cut -d':' -f1)
+
+    if [ -n "$line_number" ] && [ "$line_number" -gt 1 ]; then
+        sed -i "${line_number}s|.*|auth-user-pass $CREDENTIAL_PATH|" "$file"
+    else
+        echo "auth-user-pass $CREDENTIAL_PATH" >> "$file"
+    fi
+    echo "'auth-user-pass' updated in $file"
+}
+
+# Function to update route and route-nopull in the configuration file
+update_routes() {
+    local file=$1
+
+    # Remove existing route and route-nopull lines
+    sed -i '/^route /d' "$file"
+    sed -i '/^route-nopull/d' "$file"
+
+    local routes=()
+    if [ ${#IP_ROUTES[@]} -ne 0 ]; then
+        routes=("${IP_ROUTES[@]}" "${IP_DEFAULTS[@]}")
+    fi
+
+    # Add new route lines based on IP_ROUTES array
+    if [ ${#routes[@]} -ne 0 ]; then
+        for ip in "${routes[@]}"; do
+            echo "route $ip 255.255.255.255" >> "$file"
+        done
+        echo "route-nopull" >> "$file"
+        echo "'route' and 'route-nopull' directives updated in $file"
+    else
+        echo "No routes to add. 'route-nopull' directive not added."
+    fi
+}
+
+# Function to start OpenVPN connection
+start_openvpn() {
+    local config_file=$1
+    sudo openvpn --config "$config_file" &> "$LOG_FILE" &
+    echo "Waiting for the connection to establish..."
+
+    while :; do
+        if grep -q "Initialization Sequence Completed" "$LOG_FILE"; then
+            echo "OpenVPN connection established."
+            return 0
+        elif grep -q "AUTH_FAILED" "$LOG_FILE"; then
+            echo "Authentication failed. Exiting..."
+            cleanup_and_exit
+        fi
+        sleep 1
+    done
+}
+
+# Main script execution
+selected_file=$(select_vpn_config)
+
+if [ -z "$selected_file" ]; then
     echo "No file selected. Exiting..."
     exit 1
 fi
-echo "'vpn-config' $selected_filename"
+echo "Selected VPN config: $selected_file"
 
-# Get the line number of 'auth-user-pass' in the selected file
-line_number=$(grep -n 'auth-user-pass.*' "$selected_file" | cut -d':' -f1)
+update_auth_user_pass "$selected_file"
+update_routes "$selected_file"
 
-# Check if the line exists and is not the first line
-if [ -n "$line_number" ] && [ "$line_number" -gt 1 ]; then
-    # Replace the line above 'auth-user-pass' with the path to credential.txt
-    sed -i "${line_number}s|.*|auth-user-pass $credential_path|" "$selected_file"
-    echo "'auth-user-pass' changed!"
-else
-    # If 'auth-user-pass' doesn't exist, append it to the end of the file
-    echo "auth-user-pass $credential_path" >> "$selected_file"
-    echo "'auth-user-pass' changed!"
-fi
-
-# Connect to OpenVPN using the selected configuration file
-if sudo openvpn --config "$selected_file" &> /tmp/openvpn.log & then
-    # Wait for the connection to be established
-    echo "Waiting for the connection to establish..."
-    # Wait for a few seconds for the log file to be populated
-    while ! pgrep -x "openvpn" > /dev/null; do sleep 1; done
-
-    # Store the process ID of the OpenVPN connection
-    openvpn_pid=$!
-
-    # Continuously monitor the log file for the desired text
-    while :; do
-        if grep -q "Initialization Sequence Completed" /tmp/openvpn.log; then
-            echo "OpenVPN connection established."
-            # Perform additional actions here if needed
-            break  # Exit the loop when successful
-        elif grep -q "AUTH_FAILED" /tmp/openvpn.log; then
-            echo "Authentication failed. Exiting..."
-            # Kill the OpenVPN connection process
-            sudo kill "$openvpn_pid"
-            exit 1
-        fi
-        sleep 1  # Wait for a short interval before checking again
-    done
-
-    # Connection established, proceed with the command to check external IP
+if start_openvpn "$selected_file"; then
     echo "Checking external IP..."
     curl ipinfo.io
     echo ""
 else
     echo "Failed to establish OpenVPN connection using $selected_file."
+    exit 1
 fi
 
-# Wait for user input to stop the OpenVPN connection
 read -rp "Press Enter to stop the OpenVPN connection..."
 
-# Kill all running OpenVPN processes
-# Kill all running OpenVPN processes
-if pgrep openvpn >/dev/null; then
-    if sudo pkill openvpn; then
-        echo "All OpenVPN processes killed."
-    else
-        echo "Failed to kill OpenVPN processes."
-    fi
-fi
+# Clean up OpenVPN processes
+cleanup_and_exit
